set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i686)

# 设置编译器，使用 CMAKE_<LANG>_COMPILER_TARGET
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER_TARGET i686-pc-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET i686-pc-linux-gnu)

# 设置 C 和 CXX 标志
set(CMAKE_C_FLAGS "-m32" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "-m32" CACHE STRING "" FORCE)